name: MLSpeech4MH
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
  - conda-forge
dependencies:
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.7.0=py39haa95532_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h827c3e9_1
  - asttokens=3.0.0=py39haa95532_0
  - async-lru=2.0.4=py39haa95532_0
  - attrs=24.3.0=py39haa95532_0
  - babel=2.16.0=py39haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.3=py39haa95532_0
  - blas=1.0=mkl
  - bleach=6.2.0=py39haa95532_0
  - boost-cpp=1.82.0=h59b6b97_2
  - bottleneck=1.4.2=py39hc99e966_0
  - brotli-python=1.0.9=py39h5da7b33_9
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.12=h4c7d964_0
  - cairo=1.16.0=hc68a040_5
  - catalogue=2.0.10=py39hcbf5309_1
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py39h827c3e9_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.8=pyh7428d3b_0
  - cloudpathlib=0.21.1=pyhd8ed1ab_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=py39haa95532_0
  - comm=0.2.1=py39haa95532_0
  - confection=0.1.5=pyhecae5ae_0
  - contourpy=1.2.1=py39h214f63a_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - cython-blis=1.3.0=py39h4b0a98a_0
  - debugpy=1.8.11=py39h5da7b33_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - conda-forge::spacy-model-en_core_web_sm
  - exceptiongroup=1.2.0=py39haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h8ddb27b_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=hb33846d_3
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.55.3=py39h827c3e9_0
  - freeglut=3.4.0=hd77b12b_0
  - freetype=2.13.3=h0620614_0
  - fribidi=1.0.10=h62dcd97_0
  - getopt-win32=0.1=h2bbff1b_0
  - giflib=5.2.2=h7edc060_0
  - glib=2.78.4=hd77b12b_0
  - glib-tools=2.78.4=hd77b12b_0
  - graphite2=1.3.14=hd77b12b_1
  - graphviz=2.50.0=h13c2760_2
  - gts=0.7.6=h63ab5a1_3
  - h11=0.14.0=py39haa95532_0
  - harfbuzz=10.2.0=hf458a27_0
  - httpcore=1.0.2=py39haa95532_0
  - httpx=0.28.1=py39haa95532_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.7=py39haa95532_0
  - importlib-metadata=8.5.0=py39haa95532_0
  - importlib_metadata=8.5.0=hd3eb1b0_0
  - importlib_resources=6.4.0=py39haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.29.5=py39haa95532_1
  - ipython=8.15.0=py39haa95532_0
  - ipywidgets=8.1.5=py39haa95532_0
  - jedi=0.19.2=py39haa95532_0
  - jinja2=3.1.6=py39haa95532_0
  - joblib=1.4.2=py39haa95532_0
  - jpeg=9e=h827c3e9_3
  - json5=0.9.25=py39haa95532_0
  - jsonschema=4.23.0=py39haa95532_0
  - jsonschema-specifications=2023.7.1=py39haa95532_0
  - jupyter=1.1.1=py39haa95532_0
  - jupyter-lsp=2.2.5=py39haa95532_0
  - jupyter_client=8.6.3=py39haa95532_0
  - jupyter_console=6.6.3=py39haa95532_0
   jupyter_core=5.7.2=py39haa95532_0
  - jupyter_events=0.12.0=py39haa95532_0
  - jupyter_server=2.10.0=py39haa95532_0
  - jupyter_server_terminals=0.5.3=py39haa95532_0
  - jupyterlab=4.3.4=py39haa95532_0
  - jupyterlab_pygments=0.3.0=py39haa95532_0
  - jupyterlab_server=2.27.3=py39haa95532_0
  - jupyterlab_widgets=3.0.13=py39haa95532_0
  - kiwisolver=1.4.4=py39hd77b12b_0
  - krb5=1.20.1=h5b6d351_0
  - langcodes=3.4.1=pyhd8ed1ab_1
  - language-data=1.3.0=pyhff2d567_0
  - lcms2=2.16=h62be587_1
  - lerc=4.0.0=h5da7b33_0
  - libboost=1.82.0=h3399ecb_2
  - libcurl=8.12.1=h9da9810_0
  - libdeflate=1.22=h5bf469e_0
  - libffi=-3.4.4=hd77b12b_1
  - libgd=2.3.3=hd9a01a5_4
  - libglib=2.78.4=ha17d25a_0
  - libiconv=1.16=h2bbff1b_3
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.4=h70ee33d_0
  - libsodium=1.0.18=h62dcd97_0
  - libssh2=1.11.1=h2addb87_0
  - libtiff=4.7.0=h404307b_0
  - libwebp=1.3.2=h18467be_1
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.8=h866ff63_0
  - luigi=3.0.3=py39haa95532_0
  - lz4-c=1.9.4=h2bbff1b_1
  - marisa-trie=1.2.1=py39ha51f57c_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py39h827c3e9_0
  - matplotlib=3.9.2=py39haa95532_1
  - matplotlib-base=3.9.2=py39he19b0ae_1
  - matplotlib-inline=0.1.6=py39haa95532_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mistune=3.1.2=py39haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py39h827c3e9_2
  - mkl_fft=1.3.11=py39h827c3e9_0
  - mkl_random=1.2.8=py39hc64d2fc_0
  - nbclient=0.10.2=py39haa95532_0
  - nbconvert=7.16.6=py39haa95532_0
  - nbconvert-core=7.16.6=py39haa95532_0
  - nbconvert-pandoc=7.16.6=py39haa95532_0
  - nbformat=5.10.4=py39haa95532_0
  - nest-asyncio=1.6.0=py39haa95532_0
  - networkx=3.2.1=py39haa95532_0
  - notebook=7.3.2=py39haa95532_0
  - notebook-shim=0.2.4=py39haa95532_0
  - numexpr=2.10.1=py39h4cd664f_0
  - numpy=2.0.2=py39h055cbcc_0
  - numpy-base=2.0.2=py39h65a83cf_0
  - openjpeg=2.5.2=h9b5d1b5_1
  - openssl=3.6.0=h725018a_0
  - overrides=7.4.0=py39haa95532_0
  - packaging=24.2=py39haa95532_0
  - pandas=2.2.3=py39h5da7b33_0
  - pandoc=2.12=haa95532_3
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - pango=1.50.7=h2f82192_1
  - parso=0.8.4=py39haa95532_0
  - pcre2=10.42=h0ff8eda_1
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=11.1.0=py39hea0d53e_1
  - pip
  - pixman=0.40.0=h2bbff1b_1
  - platformdirs=4.3.7=py39haa95532_0
  - poppler=24.09.0=h89719ba_2
  - poppler-data=0.4.11=haa95532_1
  - prometheus_client=0.5.0=py_0
  - prompt-toolkit=3.0.43=py39haa95532_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py39h827c3e9_1
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pybind11-abi=5=hd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydot=3.0.4=py39haa95532_0
  - pygments=2.19.1=py39haa95532_0
  - pyparsing=3.2.0=py39haa95532_0
  - pyqt=6.7.1=py39h5da7b33_1
  - pyqt6-sip=13.9.1=py39h827c3e9_1
  - pysocks=1.7.1=py39haa95532_0
  - python=3.9.21=h8205438_1
  - python-dateutil=2.9.0post0=py39haa95532_2
  - python-fastjsonschema=2.20.0=py39haa95532_0
  - python-json-logger=3.2.1=py39haa95532_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytz=2024.1=py39haa95532_0
  - pywin32=308=py39h5da7b33_0
  - pywinpty=2.0.15=py39h72d21ff_0
  - pyyaml=6.0.2=py39h827c3e9_0
  - pyzmq=26.2.0=py39h5da7b33_0
  - qtbase=6.7.3=h0804d20_0
  - qtconsole=5.6.1=py39haa95532_1
  - qtdeclarative=6.7.3=h5da7b33_0
  - qtpy=2.4.1=py39haa95532_0
  - qtsvg=6.7.3=hf2fb9eb_0
  - qttools=6.7.3=h0de5f00_0
  - qtwebchannel=6.7.3=h5da7b33_0
  - qtwebsockets=6.7.3=h5da7b33_0
  - referencing=0.30.2=py39haa95532_0
  - requests=2.32.3=py39haa95532_1
  - rfc3339-validator=0.1.4=py39haa95532_0
  - rfc3986-validator=0.1.1=py39haa95532_0
  - rpds-py=0.22.3=py39h636fa0f_0
  - scikit-learn=1.6.1=py39h585ebfc_0
  - scipy=1.13.1=py39h8640f81_1
  - send2trash=1.8.2=py39haa95532_1
  - setuptools=72.1.0=py39haa95532_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - sip=6.10.0=py39h5da7b33_0
  - six=1.17.0=py39haa95532_0
  - smart-open=7.3.0.post1=h87fe6b5_0
  - smart_open=7.3.0.post1=pyhe01879c_0
  - sniffio=1.3.0=py39haa95532_0
  - soupsieve=2.5=py39haa95532_0
  - spacy=3.8.7=py39h99e8e5d_0
  - spacy-legacy=3.0.12=pyhd8ed1ab_0
  - spacy-loggers=1.0.5=pyhd8ed1ab_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=h59b6b97_0
  - tenacity=6.3.1=py39haa95532_0
  - terminado=0.17.1=py39haa95532_0
  - threadpoolctl=3.5.0=py39h9909e9c_0
  - tinycss2=1.4.0=py39haa95532_0
  - tomli=2.0.1=py39haa95532_0
  - tornado=6.4.2=py39h827c3e9_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=py39haa95532_0
  - typer=0.16.1=pyhc167863_0
  - typer-slim=0.16.1=pyhe01879c_0
  - typer-slim-standard=0.16.1=h810d63d_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.26100.0=h57928b3_0
  - ujson=5.10.0=py39ha51f57c_1
  - unicodedata2=15.1.0=py39h827c3e9_1
  - urllib3=2.3.0=py39haa95532_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - vs2015_runtime=14.44.35208=h38c0c73_32
  - wasabi=1.1.3=pyhd8ed1ab_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - weasel=0.4.1=pyhd8ed1ab_2
  - webencodings=0.5.1=py39haa95532_1
  - websocket-client=1.8.0=py39haa95532_0
  - wheel=0.45.1=py39haa95532_0
  - widgetsnbextension=4.0.13=py39haa95532_0
  - win_inet_pton=1.1.0=py39haa95532_0
  - winpty=0.4.3=4
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=hd77b12b_0
  - zipp=3.21.0=py39haa95532_0
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.6=h8880b57_0
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - audeer==2.2.1
      - audformat==1.3.1
      - audinterface==1.2.3
      - audiofile==1.5.1
      - audmath==1.4.1
      - audobject==0.7.11
      - audresample==1.3.3
      - category-encoders==2.6.4
      - ffmpeg==1.4
      - filelock==3.19.1
      - flatbuffers==25.2.10
      - fsspec==2025.10.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.74.0
      - h5py==3.14.0
      - imbalanced-learn==0.12.4
      - imblearn==0.0
      - iso3166==2.1.1
      - iso639-lang==2.6.0
      - keras==3.10.0
      - libclang==18.1.1
      - llvmlite==0.43.0
      - logmmse==1.5
      - markdown==3.8.2
      - ml-dtypes==0.5.3
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - mrmr-selection==0.2.8
      - namex==0.1.0
      - ndjson==0.3.1
      - numba==0.60.0
      - openai-whisper==20250625
      - opensmile==2.5.1
      - opt-einsum==3.4.0
      - optree==0.17.0
      - oyaml==1.0
      - patsy==1.0.1
      - pip==25.3
      - polars==1.32.2
      - protobuf==5.29.5
      - pyaml==25.5.0
      - pyarrow==20.0.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydub==0.25.1
      - regex==2025.11.3
      - rich==14.1.0
      - scikit-optimize==0.10.2
      - soundfile==0.13.1
      - statsmodels==0.14.5
      - sympy==1.14.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.1.0
      - tiktoken==0.12.0
      - torch==2.8.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xgboost==2.1.4
prefix: C:\Users\janeh\anaconda3\envs\youthdass
